@startuml
package "Mall" {
    [展示素材]
    [用户上传身份证图片]
}

node dubbo1 {
    [分布式服务调度1]
    [展示素材] --> [分布式服务调度1]
}

node dubbo2 {
    [分布式服务调度2]

    [用户上传身份证图片] --> [分布式服务调度2]
}

package OPE {
    frame SpringMVC {
        [素材后台维护服务]
    }

    frame dubbo {
           [身份证上传服务]
           [素材前端展示服务]

           [分布式服务调度1] --> [素材前端展示服务]
           [分布式服务调度2] --> [身份证上传服务]
       }
}

database MySql  {
   [t_idcard]
   [t_material]

    [素材后台维护服务] ----> [t_material]
    [素材前端展示服务] ----> [t_material]
    [身份证上传服务] ----> [t_idcard]

}

cloud 阿里云OSS {
    folder 身份证图 {
        [201801]
        [201802]
    }

    folder 素材图 {
            [201803]
            [201804]
    }
    [素材后台维护服务] ....> 素材图
    [身份证上传服务] ....> 身份证图
}

@enduml