@startuml
left to right direction
actor 采购
actor 运营
actor 门店
actor 消费者
采购 ----> (上架)
采购 ----> (设置成本价)

运营 ----> (设置利润)
门店 ----> (设置利润)

消费者 ----> (购买)

(上架) ----> (商品)
(设置成本价) ----> (商品)
(设置利润) ----> (商品)
(购买) ----> (商品)
@enduml