@startuml
|PC|
start
:查询首页活动信息;

  |#00CD66|MALL|
:提供活动信息查询服务;
  |#009A66|Disconf|
 :读取配置中活动信息;
 |MALL|
 :读取配置中活动信息;
 :通过指定key活动pageId查询缓存信息;
if(查询缓存中是否有信息?) then(否)
:通过活动id查询t_ta_homepage_content表
获取所有'流程信息;
 :根据限制条件过滤出能展示的楼层;
 :得到楼层中的商品列表;
 :数据组装得到20个商品id列表;
  |#00CDF6|cache|
 :将商品id列表放入缓存;
  else(是)
  endif
  |MALL|
 :查询商品接口;
  |#63B8FF|ICP|
 :商品基础信息服务;
  |MALL|
  :得到商品基础信息;
  :查询商品价格信息;
  |#007A25|HPC|
  :商品价格信息服务;
  |MALL|
   :得到商品基础信息;
   :组装商品数据模型;
   |PC|
    :展示首页商品数据模型;

  stop
@enduml