@startuml
package "微信" {
    [微小店模板活动]

}
package "app" {
    [app展示模板活动]
}
package "pc" {
    [pc展示模板活动]
}
package "mall2c" {
    [2c模板服务活动]
    [微小店模板活动] --> [2c模板服务活动]
}
package "ytms" {
    [前端群组管理]
    [组件管理]
    [活动管理]
    [楼层管理]
}
package "mall" {
    frame yt_mall_ta_client {
            [模板活动 获取活动&过滤&构建服务]
            [模板活动 获取楼层&过滤&构建服务]
            [2c模板服务活动] --->  [模板活动 获取活动&过滤&构建服务]
            [app展示模板活动] --->  [模板活动 获取活动&过滤&构建服务]
            [pc展示模板活动] --->  [模板活动 获取活动&过滤&构建服务]
            [2c模板服务活动] --->   [模板活动 获取楼层&过滤&构建服务]
            [app展示模板活动] --->   [模板活动 获取楼层&过滤&构建服务]
            [pc展示模板活动] --->  [模板活动 获取楼层&过滤&构建服务]
        }
    frame yt_mall_service_api {
            [模板活动 获取活动服务]
            [模板活动 获取楼层服务]
            [模板活动 保存服务]
            [模板活动 获取活动&过滤&构建服务] --->  [模板活动 获取活动服务]
            [模板活动 获取活动&过滤&构建服务] ---> [模板活动 获取楼层服务]
            [模板活动 获取楼层&过滤&构建服务] ---> [模板活动 获取楼层服务]
            [楼层管理] ---> [获取楼层服务]
            [活动管理] ---> [获取楼层服务]
            [楼层管理] ---> [模板活动 保存服务]
            [活动管理] ---> [模板活动 保存服务]

        }
}

database Mall库  {
   [t_ta_page]
   [t_ta_storey]
   [模板活动 保存服务] --->  [t_ta_page]
   [模板活动 保存服务] ---> [t_ta_storey]
}

database YTMS_DB  {
   [yt_storey_module]
   [活动管理] ----> [yt_storey_module]
   [楼层管理] ----> [yt_storey_module]

}


@enduml