@startuml
left to right direction
actor 运营
actor 前端开发

运营 ----> (模板活动管理)

前端开发 ----> (组件开发管理)
前端开发 ----> (前端群组管理)

(模板活动管理) --> (选择模板)
(模板活动管理) --> (查看模板详情)
(模板活动管理) --> (新建/编辑)
(模板活动管理) --> (ytms活动预览)
(模板活动管理) --> (h5浏览/pc浏览)
(新建/编辑) --> (楼层)
(新建/编辑) --> (模块)
(楼层)  --> (标题栏)
(楼层)  --> (通货行情-大贸)
(楼层)  --> (文字描述)
(楼层)  --> (商品活动列表)
(楼层)  --> (。。。)
(组件开发管理) --> (维护模块)
(组件开发管理) --> (维护模板)
(组件开发管理) --> (维护插件)
(组件开发管理) --> (h5编辑器)
@enduml